project:
  type: website
  output-dir: docs

website:
  title: "Mia Pham's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.qmd
        text: STAT-244SC

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

